# Generated by Django 6.0.6 on 2026-07-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_type', models.IntegerField()),
                ('sleep_hours', models.FloatField()),
                ('study_hours', models.FloatField()),
                ('social_media_hours', models.FloatField()),
                ('attendance', models.FloatField()),
                ('exam_pressure', models.FloatField()),
                ('family_support', models.FloatField()),
                ('month', models.IntegerField()),
                ('predicted_stress', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
